[[redirects]]
  from = "/TEST001b/*"
  to = "https://poc-website-b.netlify.app/:splat"
  status = 200

[[redirects]]
  from = "/TEST001a/*"
  to = "/:splat"
  status = 200

[[redirects]]
  from = "/*"
  query = {experiment = ":id"}
  to = "/:id/:splat"
  status = 200