[[redirects]]
  from = "/TEST001b/*"
  to = "https://poc-website-b.netlify.app/:splat"
  status = 200

[[redirects]]
  from = "/TEST001a/*"
  to = "/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/:experiment/:splat"
  status = 301
  query = {experiment = ":experiment"}